# Generated by Django 4.2.7 on 2023-11-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peligros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peligro',
            name='url_pdf',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='peligro',
            name='latitud',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='peligro',
            name='longitud',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
