# Generated by Django 4.2.7 on 2023-11-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peligro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinpad', models.IntegerField()),
                ('provincia', models.CharField(max_length=50)),
                ('distrito', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=50)),
                ('ubigeo', models.IntegerField()),
                ('latitud', models.CharField(max_length=15)),
                ('longitud', models.CharField(max_length=15)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Peligro',
                'verbose_name_plural': 'Peligros',
                'db_table': 'peligro',
            },
        ),
    ]
